### ISSUE TITLE
Fall through error in the binary operator for BasePoseMatrix

### ISSUE THREAD

**Issue by bokorn-bdaii** [bdaiinstitute/spatialmath-python#116]
Fall through error in the binary operator for BasePoseMatrix:

https://github.com/bdaiinstitute/spatialmath-python/blob/1b89c49395a21b5241e2f0a233e69394f3bc27b1/spatialmath/baseposematrix.py#L1632C7-L1632C7

If you want to compare the rotation of an SE3 to an SO3, it returns none as opposed to throwing an error or returning a valid value. This should probably raise an error as opposed to returning None. 

```
import numpy as np
from spatialmath import SE3, SO3

T0 = SE3()
print(T0.angdist(SO3()))
```

Could be fixed with closing else in `BasePoseMatrix._op2`
```
    else:
        raise ValueError(f'Invalid type ({right.__class__}) for binary operation with {left.__class__}')
```

**Comment by bokorn-bdaii** [comment]
Ya, of course. Feel free to push a unit test in.

**Comment by jcao-bdai** [comment]
@bokorn-bdaii pushed.  thanks! :crossed_fingers:

**Comment by jcao-bdai** [comment]
@bokorn-bdaii your PR fixing this issue has been merged: https://github.com/bdaiinstitute/spatialmath-python/pull/117
